default_agent: expense_claim_processor
agents:
  Expense_claim_processor:
    name: Expense_claim_processor
    entrypoint: /mnt/custom-file-systems/efs/fs-0c79fb38866a71511_fsap-0c8239828e70344e0/Agents_Workshop/Agents/doc_processing/src/main_AgentCore.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: 072851894905
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
  expense_claim_processor:
    name: expense_claim_processor
    entrypoint: /mnt/custom-file-systems/efs/fs-0c79fb38866a71511_fsap-0c8239828e70344e0/Agents_Workshop/Agents/doc_processing/src/main_AgentCore.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::072851894905:role/AgentCoreRuntimeWorkshop-1757982751
      execution_role_auto_create: false
      account: 072851894905
      region: us-east-1
      ecr_repository: 072851894905.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-expense_claim_processor
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: expense_claim_processor-knApUhGbs5
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:072851894905:runtime/expense_claim_processor-knApUhGbs5
      agent_session_id: edb7cf80-095c-4671-9524-61930d152eea
    codebuild:
      project_name: bedrock-agentcore-expense_claim_processor-builder
      execution_role: arn:aws:iam::072851894905:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-6cdc0d2841
      source_bucket: bedrock-agentcore-codebuild-sources-072851894905-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
